#DAY 7 - HTTP REQUESTS IN PYTHON
#BUILD:Directory Brute Force
#BUILD:Hash Cracker
#USE OF REQUEST LIBRARY
#HTTP REQUEST SEND OR RECEIVE
#REQUESTS.GET(URL) - SEND
#REQUESTS.POST(URL, DATA=...) = SUBMITS DATA TO SERVER
#THEN A CODE IS RECEIVED FOR STATUS OF THE SERVER
#METADATA -  HEADERS&CONTENT - INCLUDES RESPONSES - RESPONSE.STATUS_CODE RESPONSE.HEADERS RESPONSE.TEXT

