#DAY 29 - 30 OF OUR SERIES 1 AUGUST AFTER A HUGE GAP OF 13 DAYS I GUESS LETS CONTINUE FROM OUR COLLEGE.
#TODAY LETS SEE HOW WE USE WIRESHARK AND CURL TO TAKE INFO ABOUT A URL AND HOW PACKETS ARE TRAVELLING AROUND SYSTEMS.
#START WITH WIRESHARK IT'S A TOOL THAT PROVIDES THE INFORMATION OF EVERY PACKET BEING RECEIVED TO MY SYSTEM WHEN I VISIT ANY URL
#WIRESHARK HAS MANY TOOLS FOR SELECTIVE PACKETS TO WORK IT TELLS YOU THE SIZE OF DATA IN BYTES THAT IS IN THE PACKETS
#IT HAS FEATURES TO CHOOSE THE INTERFACE LIKE WIFI ETH0 ETH1 ETC THAT TELLS YOU IN WHICH INTERFACE WIRESHARK NEEDS TO
#WORK ON AND PROVIDE INFO ON THAT INTERFACE

# NOW ABOUT CURL IT PROVIDES WIRESHARK INFO IN THE TERMINAL IT GIVES YOU THE LAST DATA OF PACKETS THAT IS THE HTML FILES THAT
#THEN RUNS OF YOUR LAPTOP WHEN YOU OPEN THE URL SO CURL TAKES AND SHOWS THE HTML DATA OF THAT URL IN TERMINAL HAS MANY FEATURES LIKE
# -i THAT HELPS TO STUDY SERVER HEADER CONTENT TYPE AND STATUS CODE

#NOW THE 10-STEPS OF PACKETS JOURNEY
#1. THE USER INITIATES A TASK BY WRITING THE DOMAIN NAME LIKE EXAMPLE.COM IT STARTS THE PACKETS TO TRAVELING

#2. BROWSER DNS CACHE SEE IF THE URL AND HTML FILES ARE BROWSER STORED OR NOT SO THERE WOULD BE NO NEED FOR PACKETS TRAVELING
#FOR HTML CODE

#3. OS HOST FILE CHECKS - NOW THE HTML FILE IS CHECKED IF IT IS STORED IN LOCAL STORAGE SO NO NEED FOR PACKETS TRAVELLING
#FOR HTML CODE

#4. DNS QUERY RESOLVER - IF THERE IS LOCAL DATA AVAILABLE SO A DNS QUERY IS SENT TO THE ROUTER OR YOUR ISP DNS RESOLVER

#5. DNS HIERARCHY SEARCH - THE REQUEST HIERARCHY REQUEST TRAVELS FROM NAMESERVER TO TLD (.com) SERVER AND THEN FINALLY TO
# GOOGLE DNS SERVER

#6. IP ADDRESS RETURN - THE RESOLVED IP ADDRESS OF GOOGLE IS RETURNED TO THE BROWSER .

#7. TCP THREE WAY HANDSHAKE - NOW AS THE BROWSER HAS THE ADDRESS IT KNOCKS ON THE DOOR AND